### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jameslinimk** [josefjadrny/js-chess-engine#13]
Is there a way that after the AI moves, it returns its moves?

**Comment by josefjadrny** [comment]
Hi @jameslinimk, thank you for using this library.

You are using in memory version of aiMove() right? 
So what you need is something like getHistory() function which returns all played moves?

**Comment by josefjadrny** [comment]
Please try 0.7.0 where is a `getHistory()` function.

Reopen this issue if it is not something you need.

Thank you
