### ISSUE TITLE
game.moves(from) benchmark

### ISSUE THREAD

**Issue by fabthegreat** [josefjadrny/js-chess-engine#25]
HI, good job!
Have you benchmarked your game.moves(from) methods compared to the one from chessjs (with verbose: true)?
On chessjs evaluating the moves of Q alone on the board can take up to 180ms, which leads to a lack a responsiveness of the interface.
What about yours?

Thanks and regards

**Comment by josefjadrny** [comment]
Hey, thank you!

Honestly, I haven't. I created this purely for fun and there is no intention of competing with other libraries 🙂

**Comment by fabthegreat** [comment]
No pb, I will test it soon ;)
Just one more slight remark, would it be possible for you (in a next release) to use standard uci notation (lowcase for squares) instead of capitalized letters?
Thanks again for this great work

**Comment by josefjadrny** [comment]
That's a good idea, thanks for noticing. I will change it with the next major release.
