### ISSUE TITLE
using this package in an html page

### ISSUE THREAD

**Issue by urishani** [josefjadrny/js-chess-engine#26]
Hi and thanks for this package. I am trying to use this as the engine in a chess game on the browser, so no Node.js backend yet, but cannot make it work.

The code is something like this:
```
<script src="https://cdn.jsdelivr.net/npm/js-chess-engine"></script>
<script>
    game = new jsChessEngine.Game();
    game.printToConsole();
</script>
```

How would you suggest I do that?

Thanks.

**Comment by AirplanegoBrr** [comment]
You can do `const jsChessEngine = window["js-chess-engine"]`
also make sure you are using defer so you know the body is loaded
Note: `game.printToConsole()` will **NOT** work as it depends on the `process.stdout` which is not available in the browser

**Comment by urishani** [comment]
What worked for me eventually is bundling the engine and loading it in my file:
`<script src="./bundle.js"></script>
`
Also - indeed, refrain from using the printToConsole(), and for deferring execution I simply used
**<body onload="init()">** where the code is initialized:

```
let jsChessEngine;
function init() {
  .....
    jsChessEngine = jschess.jsChessEngine;
  .......
}
```

Bundling is done with this index.js file content:
```
const jsChessEngine = require('js-chess-engine');
window.jschess = { jsChessEngine };

```
