### ISSUE TITLE
Question: Adding "inCheck" value to the JSON (or similar)

### ISSUE THREAD

**Issue by blacgrail** [josefjadrny/js-chess-engine#7]
Hi!

First up, cheers for a great library with which to work. I'm very new to programming and have found this library quite welcoming and understandable for the most part.

I apologise in advance if this is not the place to ask questions like below. I'm also new to Github etiquette!

For my implementation, I need to be able to retrieve a boolean to see when the active player is in check. 

It does not _appear_ that any of the library commands or exported JSON fields give me that information. I'm using the in-memory option, in case that makes a difference.

Ideally, I would like to add a boolean field to the JSON to track this, but have tried all the things my programming-beginner brain can think of and haven't managed to make anything work.

Is there something I'm missing or something I should try to get this information?

Thanks!

**Comment by blacgrail** [comment]
If this is not the place for this question, please let me know and I can close it :)

**Comment by josefjadrny** [comment]
Hi, firstly, thank you for using this library and for your feedback.

> For my implementation, I need to be able to retrieve a boolean to see when the active player is in check.

There is no such indicator for check. I will add it to the next release (0.5.2) soon.

**Comment by josefjadrny** [comment]
It should be done. Check 0.6.0 please and let me know (or close this issue).

Thx

**Comment by blacgrail** [comment]
Hi Josef, thanks so much! That looks to be exactly what I need. I really appreciate the fast response and action here. Have a happy new year, mate. Thanks again!
