### ISSUE TITLE
Can't castle?

### ISSUE THREAD

**Issue by dragonfire535** [josefjadrny/js-chess-engine#9]
![image](https://user-images.githubusercontent.com/25068075/107213577-a1004780-69d6-11eb-8550-43fee22e3589.png)

Black is trying to castle here, but the engine isn't recognizing that he can. The castling properties are all false. Neither their rook or king have moved so I'm not sure why. Yellow highlight is White's last move.

**Comment by josefjadrny** [comment]
Hi @dragonfire535 
thank you for reporting this issue.

It should be fixed in 0.6.1

**Comment by dragonfire535** [comment]
Thank you!
